### ISSUE TITLE
Its leaving holes on the homepage after the ads.

### ISSUE THREAD

**Issue by OffXev** [kakajuro/tidytube#19]
![Screenshot 2024-11-09 102012](https://github.com/user-attachments/assets/5147a23a-f444-4640-8def-09e52614fd3a)

**Comment by kakajuro** [comment]
This is something which I've also noticed, I will be working on a fix for this asap

**Comment by kakajuro** [comment]
Fixed now! This will go live in the next update which I'm targeting the end of year for release. Sorry for the wait, have been very busy with uni.
