### ISSUE TITLE
Automatically disable autoplay

### ISSUE THREAD

**Issue by mitch1887** [kakajuro/tidytube#7]
It would be useful to have an option to automatically set this to off.
![autoplay](https://github.com/user-attachments/assets/664bc9d7-0f6c-426a-a661-d0c48c43f8a3)

**Comment by kakajuro** [comment]
I like this idea. I can implement this soon but not in the update coming shortly, most likely the one after

**Comment by kakajuro** [comment]
Added in #12
This auto disables autoplay but still allows you to change it afterwards. I imagine this is the intended behaviour. This will be live in the next update, thanks for the suggestion
