### ISSUE TITLE
Filters button does not work with "Remove popups" enabled

### ISSUE THREAD

**Issue by mitch1887** [kakajuro/tidytube#9]
When searching for videos the filters button does not do anything with the "Remove popups" option enabled:
![image](https://github.com/user-attachments/assets/ae9f0423-ac7f-4a00-a976-edf177b5c6ac)

When disabled it works again:
![image](https://github.com/user-attachments/assets/12c89e87-a974-49f7-80ed-ba3111982041)

**Comment by kakajuro** [comment]
Great catch. I believe this should be simple to fix. The next updated is scheduled for release soon so again this will be fixed in the update after the next

**Comment by kakajuro** [comment]
Fix will be live in the next update!
